# Generated by Django 3.1.3 on 2020-12-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersAuth', '0002_auto_20201205_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
